__title__ = "alchemy_sdk_py"
__description__ = "Python SDK for working with the Alchemy API."
__version__ = "0.1.1"
__author__ = "Alpha Chain"
__license__ = "MIT"
__copyright__ = "Copyright 2022 Alpha Chain"
